# -*- coding: utf-8 -*-
"""building_ar_en_translation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsAH1aNQmYGhn3EDzAmB9hxGcXn0lhLW
"""

from datasets import load_dataset

ds = load_dataset("opus100", "ar-en")

ds

ds["train"][0]

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
#model_name = "facebook/mbart-large-50-many-to-many-mmt"
#model_name = "facebook/nllb-200-distilled-600M"
model_name="Helsinki-NLP/opus-mt-ar-en"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

train_ds = ds["train"].select(range(2000))
test_ds = ds["test"].select(range(1000))

train_ds

test_ds

def preprocess(example):
    src = example["translation"]["ar"]
    tgt = example["translation"]["en"]

    model_inputs = tokenizer(
        src,
        text_target=tgt,
        truncation=True,
        padding="max_length",
        max_length=128
    )

    return model_inputs

tokenized_train = train_ds.map(preprocess)

tokenized_test = test_ds.map(preprocess)

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./model",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    num_train_epochs=2,
    eval_strategy="epoch",
    save_strategy="epoch"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test
)

trainer.train()

trainer.evaluate()

device = model.device

text = "أنا أحب الموز و لكنى اكره البرتقال"

inputs = tokenizer(text, return_tensors="pt").to(device)

outputs = model.generate(
    **inputs,
    max_length=50
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

trainer.save_model("./my_model")
tokenizer.save_pretrained("./my_model")

!zip -r my_model.zip /content/my_model

from google.colab import files
files.download("my_model.zip")

model.push_to_hub("Basma21/my-model")
tokenizer.push_to_hub("Basma21/my-model")